import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'mr' | 'ml';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.controls': 'Controls',
    'nav.logs': 'Logs',
    'nav.subscription': 'Subscription',
    'dashboard.title': 'Grevo Control Panel',
    'dashboard.subtitle': 'Monitor and Control Your Smart Farming Robot',
    'dashboard.status': 'Raspberry Pi Connected',
    'dashboard.systemActive': 'System Active',
    'dashboard.soilMoisture': 'Soil Moisture',
    'dashboard.waterTank': 'Water Tank Level',
    'dashboard.obstacle': 'Obstacle Detection',
    'dashboard.systemStatus': 'System Status',
    'dashboard.plantsWatered': 'Plants Watered Today',
    'dashboard.weedsRemoved': 'Weeds Removed',
    'dashboard.hoursActive': 'Hours Active',
    'controls.title': 'Robot Controls',
    'controls.subtitle': 'Direct control of your AgriBot movements and actions',
    'controls.movement': 'Movement Controls',
    'controls.actions': 'Actions',
    'controls.forward': '↑ Forward',
    'controls.left': '← Left',
    'controls.stop': 'STOP',
    'controls.right': '→ Right',
    'controls.backward': '↓ Backward',
    'controls.water': 'Water Plants',
    'controls.weed': 'Weed Now',
    'controls.actionStatus': 'Action Status',
    'controls.motor': 'Motor',
    'controls.pump': 'Pump',
    'controls.weeder': 'Weeder',
    'controls.active': 'Active',
    'controls.standby': 'Standby',
    'controls.commandSent': 'Command Sent',
    'controls.commandDescription': 'command sent to AgriBot',
    'controls.last': 'Last',
    'logs.title': 'System Logs',
    'logs.subtitle': 'Real-time monitoring of AgriBot activities and system events',
    'logs.systemLog': 'System Log',
    'logs.live': 'LIVE',
    'logs.paused': 'PAUSED',
    'logs.pause': 'Pause',
    'logs.resume': 'Resume',
    'logs.export': 'Export',
    'logs.clear': 'Clear',
    'logs.entries': 'log entries',
    'logs.autoScroll': 'Auto-scroll enabled',
    'logs.noLogs': 'No logs available. System events will appear here.',
    'logs.systemInit': 'System initialized successfully',
    'logs.connected': 'Connected to Raspberry Pi via WiFi',
    'logs.calibration': 'Sensor calibration complete',
    'logs.obstacleDetected': 'Obstacle detected at 15cm → Motors stopped',
    'logs.tankEmpty': 'Warning: Water tank is empty - refill required',
    'widgets.soilMoisture.title': 'Soil Moisture',
    'widgets.soilMoisture.dry': 'Dry',
    'widgets.soilMoisture.moderate': 'Moderate',
    'widgets.soilMoisture.moist': 'Moist',
    'widgets.waterTank.title': 'Water Tank Level',
    'widgets.waterTank.ok': 'Tank OK',
    'widgets.waterTank.empty': 'Tank Empty',
    'widgets.waterTank.refill': 'Refill required!',
    'widgets.obstacle.title': 'Obstacle Detection',
    'widgets.obstacle.detected': 'Obstacle Detected!',
    'widgets.obstacle.clear': 'Path Clear',
    'widgets.obstacle.stopped': 'Robot stopped for safety',
    'widgets.system.title': 'System Status',
    'widgets.system.motor': 'Motor',
    'widgets.system.pump': 'Water Pump',
    'widgets.system.weeder': 'Weeder',
    'widgets.system.on': 'ON',
    'widgets.system.off': 'OFF',
    'widgets.system.activeSystems': 'Active Systems',
    'widgets.moisture.title': 'Moisture History',
    'widgets.moisture.liveUpdates': 'Live updates every 2s',
    'widgets.moisture.range': 'Range: 0-1023',
    'widgets.moisture.current': 'Current',
    'subscription.title': 'Choose Your Plan',
    'subscription.subtitle': 'Enhance your farming with our premium features',
    'subscription.base': 'Base Model',
    'subscription.premium': 'Premium Model',
    'subscription.month': 'month',
    'subscription.year': 'year',
    'subscription.popular': 'Most Popular',
    'subscription.choose': 'Choose Plan',
    'footer.text': '© 2025 Grevo - Made by Parag Bhat',
    'footer.subtitle': 'Powered by Raspberry Pi • Real-time IoT Dashboard'
  },
  hi: {
    'nav.dashboard': 'डैशबोर्ड',
    'nav.controls': 'नियंत्रण',
    'nav.logs': 'लॉग्स',
    'nav.subscription': 'सब्सक्रिप्शन',
    'dashboard.title': 'ग्रेवो नियंत्रण पैनल',
    'dashboard.subtitle': 'अपने स्मार्ट कृषि रोबोट की निगरानी और नियंत्रण करें',
    'dashboard.status': 'रास्पबेरी पाई कनेक्टेड',
    'dashboard.systemActive': 'सिस्टम सक्रिय',
    'dashboard.soilMoisture': 'मिट्टी की नमी',
    'dashboard.waterTank': 'पानी की टंकी का स्तर',
    'dashboard.obstacle': 'बाधा का पता लगाना',
    'dashboard.systemStatus': 'सिस्टम की स्थिति',
    'dashboard.plantsWatered': 'आज पानी दिए गए पौधे',
    'dashboard.weedsRemoved': 'हटाए गए खरपतवार',
    'dashboard.hoursActive': 'सक्रिय घंटे',
    'controls.title': 'रोबोट नियंत्रण',
    'controls.subtitle': 'अपने एग्रीबॉट की गतिविधियों और क्रियाओं का प्रत्यक्ष नियंत्रण',
    'controls.movement': 'गति नियंत्रण',
    'controls.actions': 'क्रियाएं',
    'controls.forward': '↑ आगे',
    'controls.left': '← बाएं',
    'controls.stop': 'रुकें',
    'controls.right': '→ दाएं',
    'controls.backward': '↓ पीछे',
    'controls.water': 'पौधों को पानी दें',
    'controls.weed': 'खरपतवार हटाएं',
    'controls.actionStatus': 'क्रिया की स्थिति',
    'controls.motor': 'मोटर',
    'controls.pump': 'पंप',
    'controls.weeder': 'निराई यंत्र',
    'controls.active': 'सक्रिय',
    'controls.standby': 'प्रतीक्षा में',
    'controls.commandSent': 'कमांड भेजा गया',
    'controls.commandDescription': 'कमांड एग्रीबॉट को भेजा गया',
    'controls.last': 'अंतिम',
    'logs.title': 'सिस्टम लॉग्स',
    'logs.subtitle': 'एग्रीबॉट गतिविधियों और सिस्टम इवेंट्स की रियल-टाइम निगरानी',
    'logs.systemLog': 'सिस्टम लॉग',
    'logs.live': 'लाइव',
    'logs.paused': 'रोका गया',
    'logs.pause': 'रोकें',
    'logs.resume': 'फिर शुरू करें',
    'logs.export': 'निर्यात',
    'logs.clear': 'साफ़ करें',
    'logs.entries': 'लॉग प्रविष्टियां',
    'logs.autoScroll': 'ऑटो-स्क्रॉल सक्षम',
    'logs.noLogs': 'कोई लॉग उपलब्ध नहीं। सिस्टम इवेंट्स यहां दिखाई देंगे।',
    'logs.systemInit': 'सिस्टम सफलतापूर्वक प्रारंभ हुआ',
    'logs.connected': 'रास्पबेरी पाई से वाईफाई के माध्यम से जुड़ाव',
    'logs.calibration': 'सेंसर कैलिब्रेशन पूर्ण',
    'logs.obstacleDetected': '15सेमी पर बाधा का पता चला → मोटर रुक गई',
    'logs.tankEmpty': 'चेतावनी: पानी की टंकी खाली है - भरने की आवश्यकता',
    'widgets.soilMoisture.title': 'मिट्टी की नमी',
    'widgets.soilMoisture.dry': 'सूखी',
    'widgets.soilMoisture.moderate': 'मध्यम',
    'widgets.soilMoisture.moist': 'नम',
    'widgets.waterTank.title': 'पानी की टंकी का स्तर',
    'widgets.waterTank.ok': 'टंकी ठीक है',
    'widgets.waterTank.empty': 'टंकी खाली',
    'widgets.waterTank.refill': 'भरने की आवश्यकता!',
    'widgets.obstacle.title': 'बाधा का पता लगाना',
    'widgets.obstacle.detected': 'बाधा मिली!',
    'widgets.obstacle.clear': 'रास्ता साफ',
    'widgets.obstacle.stopped': 'सुरक्षा के लिए रोबोट रुका',
    'widgets.system.title': 'सिस्टम की स्थिति',
    'widgets.system.motor': 'मोटर',
    'widgets.system.pump': 'वाटर पंप',
    'widgets.system.weeder': 'निराई यंत्र',
    'widgets.system.on': 'चालू',
    'widgets.system.off': 'बंद',
    'widgets.system.activeSystems': 'सक्रिय सिस्टम',
    'widgets.moisture.title': 'नमी का इतिहास',
    'widgets.moisture.liveUpdates': 'हर 2 सेकंड में लाइव अपडेट',
    'widgets.moisture.range': 'रेंज: 0-1023',
    'widgets.moisture.current': 'वर्तमान',
    'subscription.title': 'अपना प्लान चुनें',
    'subscription.subtitle': 'हमारी प्रीमियम सुविधाओं के साथ अपनी खेती को बढ़ाएं',
    'subscription.base': 'बेस मॉडल',
    'subscription.premium': 'प्रीमियम मॉडल',
    'subscription.month': 'महीना',
    'subscription.year': 'साल',
    'subscription.popular': 'सबसे लोकप्रिय',
    'subscription.choose': 'प्लान चुनें',
    'footer.text': '© 2025 ग्रेवो - पराग भट द्वारा निर्मित',
    'footer.subtitle': 'रास्पबेरी पाई द्वारा संचालित • रियल-टाइम IoT डैशबोर्ड'
  },
  mr: {
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.controls': 'नियंत्रण',
    'nav.logs': 'लॉग्ज',
    'nav.subscription': 'सबस्क्रिप्शन',
    'dashboard.title': 'ग्रेवो नियंत्रण पॅनेल',
    'dashboard.subtitle': 'तुमच्या स्मार्ट शेती रोबोटचे निरीक्षण आणि नियंत्रण करा',
    'dashboard.status': 'रास्पबेरी पाई कनेक्ट केले',
    'dashboard.systemActive': 'सिस्टम सक्रिय',
    'dashboard.soilMoisture': 'मातीची ओलावा',
    'dashboard.waterTank': 'पाण्याच्या टाकीची पातळी',
    'dashboard.obstacle': 'अडथळा शोधणे',
    'dashboard.systemStatus': 'सिस्टमची स्थिती',
    'dashboard.plantsWatered': 'आज पाणी दिलेली झाडे',
    'dashboard.weedsRemoved': 'काढलेले तण',
    'dashboard.hoursActive': 'सक्रिय तास',
    'controls.title': 'रोबोट नियंत्रण',
    'controls.subtitle': 'तुमच्या एग्रीबॉटच्या हालचाली आणि क्रियांचे थेट नियंत्रण',
    'controls.movement': 'हालचाल नियंत्रण',
    'controls.actions': 'कृती',
    'controls.forward': '↑ पुढे',
    'controls.left': '← डावीकडे',
    'controls.stop': 'थांबा',
    'controls.right': '→ उजवीकडे',
    'controls.backward': '↓ मागे',
    'controls.water': 'झाडांना पाणी द्या',
    'controls.weed': 'तण काढा',
    'controls.actionStatus': 'क्रिया स्थिती',
    'controls.motor': 'मोटर',
    'controls.pump': 'पंप',
    'controls.weeder': 'तण काढणारे यंत्र',
    'controls.active': 'सक्रिय',
    'controls.standby': 'प्रतीक्षेत',
    'controls.commandSent': 'कमांड पाठवले',
    'controls.commandDescription': 'कमांड एग्रीबॉटला पाठवले',
    'controls.last': 'शेवटचे',
    'logs.title': 'सिस्टम लॉग्ज',
    'logs.subtitle': 'एग्रीबॉट क्रियाकलाप आणि सिस्टम इव्हेंट्सचे रियल-टाइम निरीक्षण',
    'logs.systemLog': 'सिस्टम लॉग',
    'logs.live': 'लाइव्ह',
    'logs.paused': 'थांबवले',
    'logs.pause': 'थांबवा',
    'logs.resume': 'पुन्हा सुरू करा',
    'logs.export': 'निर्यात',
    'logs.clear': 'साफ करा',
    'logs.entries': 'लॉग नोंदी',
    'logs.autoScroll': 'ऑटो-स्क्रॉल सक्षम',
    'logs.noLogs': 'कोणतेही लॉग उपलब्ध नाहीत. सिस्टम इव्हेंट्स येथे दिसतील.',
    'logs.systemInit': 'सिस्टम यशस्वीरित्या सुरू झाले',
    'logs.connected': 'रास्पबेरी पाईशी वाय-फायद्वारे कनेक्शन',
    'logs.calibration': 'सेन्सर कॅलिब्रेशन पूर्ण',
    'logs.obstacleDetected': '15सेमी वर अडथळा सापडला → मोटर्स थांबल्या',
    'logs.tankEmpty': 'चेतावणी: पाण्याची टाकी रिकामी आहे - भरणे आवश्यक',
    'widgets.soilMoisture.title': 'मातीची ओलावा',
    'widgets.soilMoisture.dry': 'कोरडी',
    'widgets.soilMoisture.moderate': 'मध्यम',
    'widgets.soilMoisture.moist': 'ओलसर',
    'widgets.waterTank.title': 'पाण्याच्या टाकीची पातळी',
    'widgets.waterTank.ok': 'टाकी ठीक',
    'widgets.waterTank.empty': 'टाकी रिकामी',
    'widgets.waterTank.refill': 'भरणे आवश्यक!',
    'widgets.obstacle.title': 'अडथळा शोधणे',
    'widgets.obstacle.detected': 'अडथळा सापडला!',
    'widgets.obstacle.clear': 'रस्ता मोकळा',
    'widgets.obstacle.stopped': 'सुरक्षिततेसाठी रोबोट थांबला',
    'widgets.system.title': 'सिस्टमची स्थिती',
    'widgets.system.motor': 'मोटर',
    'widgets.system.pump': 'वॉटर पंप',
    'widgets.system.weeder': 'तण काढणारे यंत्र',
    'widgets.system.on': 'चालू',
    'widgets.system.off': 'बंद',
    'widgets.system.activeSystems': 'सक्रिय सिस्टम',
    'widgets.moisture.title': 'ओलाव्याचा इतिहास',
    'widgets.moisture.liveUpdates': 'दर २ सेकंदांनी लाइव्ह अपडेट्स',
    'widgets.moisture.range': 'रेंज: 0-1023',
    'widgets.moisture.current': 'सध्याचे',
    'subscription.title': 'तुमचा प्लॅन निवडा',
    'subscription.subtitle': 'आमच्या प्रीमियम वैशिष्ट्यांसह तुमची शेती वाढवा',
    'subscription.base': 'बेस मॉडेल',
    'subscription.premium': 'प्रीमियम मॉडेल',
    'subscription.month': 'महिना',
    'subscription.year': 'वर्ष',
    'subscription.popular': 'सर्वाधिक लोकप्रिय',
    'subscription.choose': 'प्लॅन निवडा',
    'footer.text': '© 2025 ग्रेवो - पराग भट यांनी बनवले',
    'footer.subtitle': 'रास्पबेरी पाई द्वारे चालवले • रियल-टाइम IoT डॅशबोर्ड'
  },
  ml: {
    'nav.dashboard': 'ഡാഷ്‌ബോർഡ്',
    'nav.controls': 'നിയന്ത്രണങ്ങൾ',
    'nav.logs': 'ലോഗുകൾ',
    'nav.subscription': 'സബ്‌സ്ക്രിപ്‌ഷൻ',
    'dashboard.title': 'ഗ്രേവോ കൺട്രോൾ പാനൽ',
    'dashboard.subtitle': 'നിങ്ങളുടെ സ്മാർട്ട് കൃഷി റോബോട്ട് നിരീക്ഷിക്കുകയും നിയന്ത്രിക്കുകയും ചെയ്യുക',
    'dashboard.status': 'റാസ്പ്ബെറി പൈ കണക്റ്റഡ്',
    'dashboard.systemActive': 'സിസ്റ്റം സജീവം',
    'dashboard.soilMoisture': 'മണ്ണിന്റെ ഈർപ്പം',
    'dashboard.waterTank': 'വാട്ടർ ടാങ്ക് ലെവൽ',
    'dashboard.obstacle': 'തടസ്സം കണ്ടെത്തൽ',
    'dashboard.systemStatus': 'സിസ്റ്റം സ്റ്റാറ്റസ്',
    'dashboard.plantsWatered': 'ഇന്ന് വെള്ളം നൽകിയ ചെടികൾ',
    'dashboard.weedsRemoved': 'നീക്കം ചെയ്ത കളകൾ',
    'dashboard.hoursActive': 'സജീവ മണിക്കൂറുകൾ',
    'controls.title': 'റോബോട്ട് നിയന്ത്രണങ്ങൾ',
    'controls.subtitle': 'നിങ്ങളുടെ അഗ്രിബോട്ടിന്റെ ചലനങ്ങളുടെയും പ്രവർത്തനങ്ങളുടെയും നേരിട്ടുള്ള നിയന്ത്രണം',
    'controls.movement': 'ചലന നിയന്ത്രണങ്ങൾ',
    'controls.actions': 'പ്രവർത്തനങ്ങൾ',
    'controls.forward': '↑ മുന്നോട്ട്',
    'controls.left': '← ഇടത്',
    'controls.stop': 'നിർത്തുക',
    'controls.right': '→ വലത്',
    'controls.backward': '↓ പിന്നോട്ട്',
    'controls.water': 'ചെടികൾക്ക് വെള്ളം നൽകുക',
    'controls.weed': 'കളകൾ നീക്കം ചെയ്യുക',
    'controls.actionStatus': 'പ്രവർത്തന നില',
    'controls.motor': 'മോട്ടർ',
    'controls.pump': 'പമ്പ്',
    'controls.weeder': 'കള നീക്കൽ യന്ത്രം',
    'controls.active': 'സജീവം',
    'controls.standby': 'കാത്തിരിപ്പിൽ',
    'controls.commandSent': 'കമാൻഡ് അയച്ചു',
    'controls.commandDescription': 'കമാൻഡ് അഗ്രിബോട്ടിന് അയച്ചു',
    'controls.last': 'അവസാനം',
    'logs.title': 'സിസ്റ്റം ലോഗുകൾ',
    'logs.subtitle': 'അഗ്രിബോട്ട് പ്രവർത്തനങ്ങളുടെയും സിസ്റ്റം ഇവന്റുകളുടെയും റിയൽ-ടൈം നിരീക്ഷണം',
    'logs.systemLog': 'സിസ്റ്റം ലോഗ്',
    'logs.live': 'ലൈവ്',
    'logs.paused': 'നിർത്തി',
    'logs.pause': 'നിർത്തുക',
    'logs.resume': 'പുനരാരംഭിക്കുക',
    'logs.export': 'എക്സ്പോർട്ട്',
    'logs.clear': 'ക്ലിയർ ചെയ്യുക',
    'logs.entries': 'ലോഗ് എൻട്രികൾ',
    'logs.autoScroll': 'ഓട്ടോ-സ്ക്രോൾ പ്രവർത്തനക്ഷമം',
    'logs.noLogs': 'ലോഗുകളൊന്നും ലഭ്യമല്ല. സിസ്റ്റം ഇവന്റുകൾ ഇവിടെ പ്രത്യക്ഷപ്പെടും.',
    'logs.systemInit': 'സിസ്റ്റം വിജയകരമായി ആരംഭിച്ചു',
    'logs.connected': 'വൈഫൈ വഴി റാസ്പ്ബെറി പൈയിലേക്ക് കണക്ട് ചെയ്തു',
    'logs.calibration': 'സെൻസർ കാലിബ്രേഷൻ പൂർത്തിയായി',
    'logs.obstacleDetected': '15 സെമീയിൽ തടസ്സം കണ്ടെത്തി → മോട്ടറുകൾ നിർത്തി',
    'logs.tankEmpty': 'മുന്നറിയിപ്പ്: വാട്ടർ ടാങ്ക് ശൂന്യമാണ് - നിറയ്ക്കേണ്ടതുണ്ട്',
    'widgets.soilMoisture.title': 'മണ്ണിന്റെ ഈർപ്പം',
    'widgets.soilMoisture.dry': 'വരണ്ടത്',
    'widgets.soilMoisture.moderate': 'മിതമായത്',
    'widgets.soilMoisture.moist': 'നനഞ്ഞത്',
    'widgets.waterTank.title': 'വാട്ടർ ടാങ്ക് ലെവൽ',
    'widgets.waterTank.ok': 'ടാങ്ക് ശരി',
    'widgets.waterTank.empty': 'ടാങ്ക് ശൂന്യം',
    'widgets.waterTank.refill': 'നിറയ്ക്കേണ്ടതുണ്ട്!',
    'widgets.obstacle.title': 'തടസ്സം കണ്ടെത്തൽ',
    'widgets.obstacle.detected': 'തടസ്സം കണ്ടെത്തി!',
    'widgets.obstacle.clear': 'പാത വ്യക്തം',
    'widgets.obstacle.stopped': 'സുരക്ഷയ്ക്കായി റോബോട്ട് നിർത്തി',
    'widgets.system.title': 'സിസ്റ്റം സ്റ്റാറ്റസ്',
    'widgets.system.motor': 'മോട്ടർ',
    'widgets.system.pump': 'വാട്ടർ പമ്പ്',
    'widgets.system.weeder': 'കള നീക്കൽ യന്ത്രം',
    'widgets.system.on': 'ഓൺ',
    'widgets.system.off': 'ഓഫ്',
    'widgets.system.activeSystems': 'സജീവ സിസ്റ്റങ്ങൾ',
    'widgets.moisture.title': 'ഈർപ്പത്തിന്റെ ചരിത്രം',
    'widgets.moisture.liveUpdates': 'ഓരോ 2 സെക്കൻഡിലും ലൈവ് അപ്ഡേറ്റുകൾ',
    'widgets.moisture.range': 'പരിധി: 0-1023',
    'widgets.moisture.current': 'നിലവിലുള്ളത്',
    'subscription.title': 'നിങ്ങളുടെ പ്ലാൻ തിരഞ്ഞെടുക്കുക',
    'subscription.subtitle': 'ഞങ്ങളുടെ പ്രീമിയം ഫീച്ചറുകൾ ഉപയോഗിച്ച് നിങ്ങളുടെ കൃഷി മെച്ചപ്പെടുത്തുക',
    'subscription.base': 'ബേസ് മോഡൽ',
    'subscription.premium': 'പ്രീമിയം മോഡൽ',
    'subscription.month': 'മാസം',
    'subscription.year': 'വർഷം',
    'subscription.popular': 'ഏറ്റവും ജനപ്രിയം',
    'subscription.choose': 'പ്ലാൻ തിരഞ്ഞെടുക്കുക',
    'footer.text': '© 2025 ഗ്രേവോ - പരാഗ് ഭട്ട് നിർമ്മിച്ചത്',
    'footer.subtitle': 'റാസ്പ്ബെറി പൈ പവർഡ് • റിയൽ-ടൈം IoT ഡാഷ്ബോർഡ്'
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};